/** S01 Bienvenida, S02/S03 auth, S04/S24 password recovery (13 §9–§10). */
export const auth = {
  welcome: {
    title: 'Cada serie, con el peso justo.',
    body: 'Te sugerimos la carga de cada serie y te explicamos por qué. Funciona sin conexión.',
    continueAsGuest: 'Continuar sin cuenta',
    signUp: 'Crear cuenta',
    signIn: 'Iniciar sesión',
  },
  form: {
    continueWithGoogle: 'Continuar con Google',
    orWithEmail: 'o con tu email',
    signIn: 'Iniciar sesión',
    forgotPassword: 'Olvidé mi contraseña',
    showPassword: 'Mostrar contraseña',
    signingIn: 'Ingresando…',
    noAccount: 'No tengo cuenta',
    signUp: 'Crear cuenta',
    haveAccount: 'Ya tengo cuenta',
    signUpBody: 'Respaldá tus entrenamientos y usalos en otro teléfono.',
    passwordHelp: 'Al menos 8 caracteres.',
    passwordTooShort: 'Tiene que tener al menos 8 caracteres.',
    emailMissingDomain: 'Revisá el email: falta el dominio (por ejemplo, .com).',
  },
  errors: {
    offline: (action: string) =>
      `Necesitás conexión para ${action}. Podés seguir entrenando sin cuenta.`,
    wrongCredentials: 'Email o contraseña incorrectos.',
    emailTaken: 'Ya existe una cuenta con este email.',
    emailTakenAction: 'Iniciar sesión',
    useYourPassword: 'Ya tenés una cuenta con este email. Entrá con tu contraseña.',
    useGoogle: 'Ya tenés una cuenta con este email. Entrá con Google.',
    otherAccount: 'Para entrar con otra cuenta, primero cerrá sesión.',
  },
  recovery: {
    title: 'Recuperar contraseña',
    body: 'Te mandamos un enlace para crear una nueva.',
    send: 'Enviar enlace',
    checkEmail: 'Revisá tu correo',
    sent: 'Enlace enviado',
    sentBody: 'Si existe una cuenta con ese email, te enviamos un enlace.',
    backToSignIn: 'Volver a iniciar sesión',
    newPasswordTitle: 'Nueva contraseña',
    newPasswordBody: 'Elegí una contraseña de al menos 8 caracteres.',
    saveAndSignIn: 'Guardar y entrar',
    linkExpiryHelp: 'Los enlaces vencen después de un tiempo o cuando ya se usaron.',
    invalidLink: 'Este enlace ya no es válido.',
    requestNewLink: 'Pedir uno nuevo',
  },
} as const;
