/** S21 Perfil, its setting sheets, S22 Acerca de, S23 Restaurando, S25 Conflictos (13 §9, §10). */
export const profile = {
  title: 'Perfil',
  guest: 'Invitado',
  noAccount: 'Sin cuenta',
  sections: { training: 'Entrenamiento', preferences: 'Preferencias' },
  rows: {
    level: 'Nivel',
    goal: 'Objetivo',
    daysPerWeek: 'Días por semana',
    unit: 'Unidad de peso',
    effort: 'Esfuerzo',
    simpleScale: 'Escala simple',
    increments: 'Incrementos de peso',
    byEquipment: 'Por equipamiento',
    restNotifications: 'Notificaciones del descanso',
    restNotificationsHelp: 'Te avisamos aunque la pantalla esté bloqueada.',
    about: 'Acerca de y créditos',
    signOut: 'Cerrar sesión',
    backUpNow: 'Respaldar ahora',
  },
  permissions: {
    notificationsBlocked:
      'Están bloqueadas en los ajustes del teléfono. Activalas ahí para que te avisemos con la pantalla bloqueada.',
    openPhoneSettings: 'Abrir ajustes del teléfono',
    exactAlarmsOff:
      'Alarmas exactas desactivadas: sin ellas no te avisamos con la pantalla bloqueada.',
    allow: 'Permitir',
  },
  increments: {
    help: 'Incrementos: Usamos estos saltos para que las sugerencias sean pesos que existen en tu gimnasio.',
    inKg: 'En kg',
    barWeight: 'Peso de la barra',
    lbNote: 'Si cambiás a lb usamos otros saltos (5 lb, 10 lb): no se convierten.',
  },
  /** Setting sheets of S21 (marca §14). */
  sheets: {
    level: 'Nivel',
    goal: 'Objetivo',
    daysPerWeek: 'Días por semana',
    unit: 'Unidad de peso',
    effort: 'Esfuerzo',
    save: 'Guardar',
    routineDoesNotChange: 'Tu rutina no cambia sola: después te preguntamos si querés ajustarla.',
    kg: { title: 'Kilos (kg)', body: 'Como se ve hoy.' },
    lb: { title: 'Libras (lb)', body: 'Para discos y mancuernas en libras.' },
    unitNote:
      'Tus datos no cambian: solo cómo se muestran y cómo cargás los pesos. Si cambiás a lb usamos otros saltos (5 lb, 10 lb): no se convierten.',
    simple: { title: 'Escala simple', body: '«¿Cuántas más podías hacer?»' },
    simpleOptions: ['Ninguna', '1', '2 o 3', '4 o más'],
    rir: {
      title: 'RIR numérico',
      body: 'Repeticiones en reserva, de 0 a 5+. Para quien ya lo usa.',
    },
    effortKept: 'Si después cambiás tu nivel, esta elección se mantiene.',
  },
  /** Backup status (RF-SYNC-06, 13 §9). */
  sync: {
    synced: (time: string) => `Respaldado · hace ${time}`,
    syncing: 'Respaldando…',
    pendingOffline: (n: number) => `${n} cambios sin respaldar · sin conexión`,
    pendingOnline: (n: number) => `${n} cambios por respaldar…`,
    workoutInProgress: 'Tu entrenamiento se respalda al finalizarlo.',
    sessionExpired: 'Tu sesión venció. Tus datos siguen en este teléfono.',
    signInAgain: 'Volver a entrar',
    conflict: (n: number) => `${n} cambios no se pudieron respaldar`,
    see: 'Ver',
    networkError: 'No pudimos respaldar. Lo intentamos de nuevo solos.',
    retry: 'Reintentar',
    guest: 'Sin respaldo: tus datos están solo en este teléfono.',
    createAccount: 'Crear cuenta',
    appOutdated: 'Actualizá la app para respaldar tus datos.',
    backUpNow: 'Respaldar ahora',
  },
  about: {
    title: 'Acerca de',
    version: (version: string) => `Versión ${version}`,
    credits: 'Créditos',
    exerciseCatalog: 'Catálogo de ejercicios',
    photos: 'Fotos',
    fonts: 'Tipografías',
    basedOn: 'En qué nos basamos',
    principlesCount: (n: number) => `${n} principios`,
    principlesHelp: 'Los principios detrás de las sugerencias y sus fuentes científicas.',
  },
  restoring: {
    title: (percent: string) => `Restaurando tus datos… ${percent}`,
    progress: (done: number, total: number) => `${done} de ${total} registros`,
    help: 'Si se corta la conexión, lo que ya bajó queda guardado y seguimos solos después.',
    interrupted: 'Se cortó la conexión',
    interruptedBody:
      'Podés seguir usando la app. Terminamos de restaurar solos cuando vuelva la conexión.',
    continue: 'Continuar',
  },
  conflicts: {
    title: 'Cambios sin respaldar',
    body: 'No pudimos respaldar estos cambios. Tocá uno para ver qué pasó y qué podés hacer.',
    empty: { title: 'Todo respaldado', body: 'No hay cambios pendientes.' },
  },
} as const;
